kwriteconfig5 --file "./conf/etc/xdg/plasma-localerc" --group "Formats" --key "LANG" "en_SG.UTF-8"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kcm_touchpad" --key "Disable Touchpad" "Touchpad Off,Touchpad Off,Disable Touchpad"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kcm_touchpad" --key "Enable Touchpad" "Touchpad On,Touchpad On,Enable Touchpad"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kcm_touchpad" --key "Toggle Touchpad" "Touchpad Toggle,Touchpad Toggle,Toggle Touchpad"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kcm_touchpad" --key "_k_friendly_name" "Touchpad"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kded5" --key "Show System Activity" "Ctrl+Esc,Ctrl+Esc,Show System Activity"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kded5" --key "_k_friendly_name" "KDE Daemon"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kded5" --key "display" "Display\tMeta+P,Display\tMeta+P,Switch Display"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "khotkeys" --key "_k_friendly_name" "Custom Shortcuts Service"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "khotkeys" --key "{2b622f4b-e7dd-4cb3-a362-b4bb59688264}" "Meta+Shift+S,none,open"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "khotkeys" --key "{e793c702-98fa-4314-98a2-9aed7662ad13}" "Alt+Media Play,none,next"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "khotkeys" --key "{f78700e1-1af3-4a00-8bfc-1abc66d68a91}" "Ctrl+Media Play,none,prev"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "_k_friendly_name" "Audio Volume"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "decrease_microphone_volume" "Microphone Volume Down,Microphone Volume Down,Decrease Microphone Volume"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "decrease_volume" "Volume Down,Volume Down,Decrease Volume"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "increase_microphone_volume" "Microphone Volume Up,Microphone Volume Up,Increase Microphone Volume"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "increase_volume" "Volume Up,Volume Up,Increase Volume"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "mic_mute" "Microphone Mute\tMeta+Volume Mute,Microphone Mute\tMeta+Volume Mute,Mute Microphone"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kmix" --key "mute" "Volume Mute,Volume Mute,Mute"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "Halt Without Confirmation" "none,,Halt Without Confirmation"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "Lock Session" "Meta+L\tCtrl+Alt+L\tScreensaver,Meta+L\tCtrl+Alt+L\tScreensaver,Lock Session"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "Log Out" "Ctrl+Alt+Del,Ctrl+Alt+Del,Log Out"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "Log Out Without Confirmation" "none,,Log Out Without Confirmation"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "Reboot Without Confirmation" "none,,Reboot Without Confirmation"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "ksmserver" --key "_k_friendly_name" "Session Management"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Expose" "Meta+Tab\tCtrl+F9,Ctrl+F9,Toggle Present Windows (Current desktop)"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "ExposeAll" "Meta+Shift+Tab\tLaunch (C)\tCtrl+F10,Ctrl+F10\tLaunch (C),Toggle Present Windows (All desktops)"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "ExposeClass" "Ctrl+F7,Ctrl+F7,Toggle Present Windows (Window class)"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Kill Window" "Ctrl+Alt+Esc,Ctrl+Alt+Esc,Kill Window"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Show Desktop" "Meta+D,Meta+D,Show Desktop"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "ShowDesktopGrid" "Ctrl+F8,Ctrl+F8,Show Desktop Grid"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Suspend Compositing" "Alt+Shift+F12,Alt+Shift+F12,Suspend Compositing"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch One Desktop Down" "Meta+Ctrl+@\tMeta+Down,Meta+Ctrl+Down,Switch One Desktop Down"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch One Desktop Up" "Meta+Up\tMeta+Ctrl+!,Meta+Ctrl+Up,Switch One Desktop Up"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch One Desktop to the Left" "Meta+Left\tMeta+Ctrl+2,Meta+Ctrl+Left,Switch One Desktop to the Left"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch One Desktop to the Right" "Meta+Right\tMeta+Ctrl+1,Meta+Ctrl+Right,Switch One Desktop to the Right"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch Window Down" "none,Meta+Alt+Down,Switch to Window Below"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch Window Left" "none,Meta+Alt+Left,Switch to Window to the Left"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch Window Right" "none,Meta+Alt+Right,Switch to Window to the Right"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Switch Window Up" "none,Meta+Alt+Up,Switch to Window Above"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows" "Alt+Tab,Alt+Tab,Walk Through Windows"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows (Reverse)" "Alt+Shift+Backtab,Alt+Shift+Backtab,Walk Through Windows (Reverse)"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows of Current Application" "Alt+\`,Alt+\`,Walk Through Windows of Current Application"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows of Current Application (Reverse)" "Alt+~,Alt+~,Walk Through Windows of Current Application (Reverse)"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Above Other Windows" "Ctrl+Alt+Shift+Up,,Keep Window Above Others"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Below Other Windows" "Ctrl+Alt+Shift+Down,,Keep Window Below Others"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Close" "Alt+F4,Alt+F4,Close Window"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Maximize" "Meta+PgUp\tMeta+],Meta+PgUp,Maximize Window"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window On All Desktops" "Ctrl+Alt+Shift+Right,,Keep Window on All Desktops"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window One Desktop Down" "Meta+Ctrl+Shift+Down\tMeta+Ctrl+Down\tMeta+Ctrl+Alt+@,Meta+Ctrl+Shift+Down,Window One Desktop Down"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window One Desktop Up" "Meta+Ctrl+Shift+Up\tMeta+Ctrl+Up\tMeta+Ctrl+Alt+!,Meta+Ctrl+Shift+Up,Window One Desktop Up"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window One Desktop to the Left" "Meta+Ctrl+Shift+Left\tMeta+Ctrl+Alt+2\tMeta+Ctrl+Left,Meta+Ctrl+Shift+Left,Window One Desktop to the Left"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window One Desktop to the Right" "Meta+Ctrl+Shift+Right\tMeta+Ctrl+Right\tMeta+Ctrl+Alt+1,Meta+Ctrl+Shift+Right,Window One Desktop to the Right"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Operations Menu" "Alt+F3,Alt+F3,Window Operations Menu"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Quick Tile Bottom" "Meta+Alt+Down,Meta+Down,Quick Tile Window to the Bottom"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Quick Tile Left" "Meta+Alt+Left,Meta+Left,Quick Tile Window to the Left"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Quick Tile Right" "Meta+Alt+Right,Meta+Right,Quick Tile Window to the Right"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window Quick Tile Top" "Meta+Alt+Up,Meta+Up,Quick Tile Window to the Top"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window to Next Screen" "Meta+Shift+Right,Meta+Shift+Right,Window to Next Screen"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "Window to Previous Screen" "Meta+Shift+Left,Meta+Shift+Left,Window to Previous Screen"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "_k_friendly_name" "KWin"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "view_actual_size" "Meta+0,Meta+0,Actual Size"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "view_zoom_in" "Meta+=,Meta+=,Zoom Out"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "kwin" --key "view_zoom_out" "Meta+-,Meta+-,Zoom Out"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "_k_friendly_name" "Media Controller"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "mediavolumedown" "none,,Media volume down"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "mediavolumeup" "none,,Media volume up"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "nextmedia" "Media Next,Media Next,Media playback next"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "pausemedia" "Media Pause,Media Pause,Pause media playback"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "playmedia" "none,,Play media playback"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "playpausemedia" "Media Play,Media Play,Play/Pause media playback"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "previousmedia" "Media Previous,Media Previous,Media playback previous"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "mediacontrol" --key "stopmedia" "Media Stop,Media Stop,Stop media playback"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.dolphin.desktop" --key "_k_friendly_name" "Dolphin"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.dolphin.desktop" --key "_launch" "Meta+E,Meta+E,Dolphin"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.konsole.desktop" --key "_k_friendly_name" "Konsole"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.konsole.desktop" --key "_launch" "Ctrl+Alt+T,none,Konsole"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.krunner.desktop" --key "RunClipboard" "Alt+Shift+F2,Alt+Shift+F2,Run command on clipboard contents"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.krunner.desktop" --key "_k_friendly_name" "KRunner"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.krunner.desktop" --key "_launch" "Alt+Space\tAlt+F2\tSearch,Alt+Space\tAlt+F2\tSearch,KRunner"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.plasma.emojier.desktop" --key "_k_friendly_name" "Emoji Selector"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org.kde.plasma.emojier.desktop" --key "_launch" "Meta+.,Meta+.,Emoji Selector"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Decrease Keyboard Brightness" "Keyboard Brightness Down,Keyboard Brightness Down,Decrease Keyboard Brightness"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Decrease Screen Brightness" "Monitor Brightness Down,Monitor Brightness Down,Decrease Screen Brightness"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Hibernate" "Hibernate,Hibernate,Hibernate"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Increase Keyboard Brightness" "Keyboard Brightness Up,Keyboard Brightness Up,Increase Keyboard Brightness"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Increase Screen Brightness" "Monitor Brightness Up,Monitor Brightness Up,Increase Screen Brightness"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "PowerDown" "Power Down,Power Down,Power Down"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "PowerOff" "Power Off,Power Off,Power Off"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Sleep" "Sleep,Sleep,Suspend"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "Toggle Keyboard Backlight" "Keyboard Light On/Off,Keyboard Light On/Off,Toggle Keyboard Backlight"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "org_kde_powerdevil" --key "_k_friendly_name" "Power Management"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "_k_friendly_name" "Plasma"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 1" "Meta+1,Meta+1,Activate Task Manager Entry 1"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 10" "none,Meta+0,Activate Task Manager Entry 10"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 2" "Meta+2,Meta+2,Activate Task Manager Entry 2"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 3" "Meta+3,Meta+3,Activate Task Manager Entry 3"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 4" "Meta+4,Meta+4,Activate Task Manager Entry 4"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 5" "Meta+5,Meta+5,Activate Task Manager Entry 5"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 6" "Meta+6,Meta+6,Activate Task Manager Entry 6"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 7" "Meta+7,Meta+7,Activate Task Manager Entry 7"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 8" "Meta+8,Meta+8,Activate Task Manager Entry 8"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "activate task manager entry 9" "Meta+9,Meta+9,Activate Task Manager Entry 9"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "show dashboard" "Ctrl+F12,Ctrl+F12,Show Desktop"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "plasmashell" --key "show-on-mouse-pos" "Meta+V,Meta+V,Open Klipper at Mouse Position"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "systemsettings.desktop" --key "_k_friendly_name" "System Settings"
kwriteconfig5 --file "./conf/etc/xdg/kglobalshortcutsrc" --group "systemsettings.desktop" --key "_launch" "Tools,Tools,System Settings"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Compositing" --key "GLCore" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Compositing" --key "OpenGLIsUnsafe" "false"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_1" "5d9883a3-5318-4c83-85db-70712ba16bb2"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_10" "9b0afee8-b349-4ad5-ae58-2188950efe1c"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_11" "6e72eacc-55c6-4792-b5c9-f5ed1a212afe"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_12" "031fdbd2-af14-4565-9aca-27262b5a29ec"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_13" "28a903a9-7aa6-4fa8-ab1d-0979d8d65d0e"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_14" "6cd1f5e0-5e1b-4f62-817f-1d84dcf54170"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_15" "47db55cd-de5c-4cf8-80a9-fd402b8a0f0a"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_16" "cd51710b-9d9b-4c4c-8ec6-ba7121a53b40"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_17" "88e28943-bdcb-44c9-83e9-9dc03154ef9b"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_18" "38a8fb28-c744-43d0-9c90-2f97c5bed6f6"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_19" "972d14b5-2582-4c50-bb8b-c5fb2b2d2959"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_2" "3253195e-4655-451c-8cd3-b5e7a3b5a6eb"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_20" "fcd2e084-8cd8-443e-9a9e-6e5a87404d7b"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_3" "d50e4bf7-8290-4dfa-88e4-c1f3d225ab09"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_4" "bcb3771d-be99-45e4-959b-4288a0004acf"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_5" "548cdecb-03f4-4bf0-8094-7cdabbfc748b"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_6" "22e8b3c8-ccce-4685-a137-036bc71ee230"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_7" "1d6d6a15-8237-4a9d-8298-47acfc0fe056"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_8" "03edf17b-a4b4-4979-8d5a-ab5fe0fac7c3"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Id_9" "43e8a1f9-6936-40e7-8651-20840064f61a"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_10" "10"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_11" "11"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_12" "12"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_13" "13"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_14" "14"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_15" "15"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_16" "16"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_17" "17"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_18" "18"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_19" "19"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_2" "2"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_20" "20"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_3" "3"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_4" "4"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_5" "5"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_6" "6"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_7" "7"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_8" "8"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Name_9" "9"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Number" "20"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Desktops" --key "Rows" "4"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Blur" --key "BlurStrength" "3"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Blur" --key "NoiseStrength" "0"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-PresentWindows" --key "BorderActivateAll" "9"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Slide" --key "SlideDocks" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Wobbly" --key "AdvancedMode" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Wobbly" --key "Drag" "85"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Wobbly" --key "Stiffness" "10"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Effect-Wobbly" --key "WobblynessLevel" "1"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "blurEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "contrastEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "kwin4_effect_dimscreenEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "kwin4_effect_translucencyEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "screenedgeEnabled" "false"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Plugins" --key "wobblywindowsEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Script-desktopchangeosd" --key "PopupHideDelay" "200"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "TabBox" --key "BorderActivate" "9"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "TabBox" --key "LayoutName" "MediumRoundedDark"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Windows" --key "ElectricBorderCooldown" "150"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "Windows" --key "ElectricBorderDelay" "100"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "org.kde.kdecoration2" --key "BorderSize" "None"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "org.kde.kdecoration2" --key "BorderSizeAuto" "false"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "org.kde.kdecoration2" --key "library" "org.kde.kwin.aurorae"
kwriteconfig5 --file "./conf/etc/xdg/kwinrc" --group "org.kde.kdecoration2" --key "theme" "__aurorae__svg__Sweet-Dark-transparent"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --key "icon" "battery-charging"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "DPMSControl" --key "idleTime" "600"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "DPMSControl" --key "lockBeforeTurnOff" "0"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "DimDisplay" --key "idleTime" "300000"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "HandleButtonEvents" --key "lidAction" "1"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "HandleButtonEvents" --key "powerButtonAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "AC" --group "HandleButtonEvents" --key "powerDownAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --key "icon" "battery-060"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "DPMSControl" --key "idleTime" "300"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "DPMSControl" --key "lockBeforeTurnOff" "0"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "DimDisplay" --key "idleTime" "120000"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "HandleButtonEvents" --key "lidAction" "1"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "HandleButtonEvents" --key "powerButtonAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "HandleButtonEvents" --key "powerDownAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "SuspendSession" --key "idleTime" "600000"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "Battery" --group "SuspendSession" --key "suspendType" "1"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --key "icon" "battery-low"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "BrightnessControl" --key "value" "30"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "DPMSControl" --key "idleTime" "120"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "DPMSControl" --key "lockBeforeTurnOff" "0"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "DimDisplay" --key "idleTime" "60000"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "HandleButtonEvents" --key "lidAction" "1"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "HandleButtonEvents" --key "powerButtonAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "HandleButtonEvents" --key "powerDownAction" "16"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "SuspendSession" --key "idleTime" "300000"
kwriteconfig5 --file "./conf/etc/xdg/powermanagementprofilesrc" --group "LowBattery" --group "SuspendSession" --key "suspendType" "1"
kwriteconfig5 --file "./conf/etc/xdg/plasmarc" --group "Wallpapers" --key "usersWallpapers" "/home1/tev/Desktop/background/Anime Street Evening.png"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Config Revision" "10"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Days Meta Infos" "30"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Save Meta Infos" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Show Full Path in Title" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Show Menu Bar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Show Status Bar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Show Tab Bar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "General" --key "Show Url Nav Bar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Allow End of Line Detection" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Auto Detect Indent" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Auto Save" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Auto Save Interval" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Auto Save On Focus Out" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "BOM" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Backup Local" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Backup Prefix" ""
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Backup Remote" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Backup Suffix" "~"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Camel Cursor" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Encoding" "UTF-8"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "End of Line" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Indent On Backspace" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Indent On Tab" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Indent On Text Paste" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Indentation Mode" "normal"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Indentation Width" "4"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Keep Extra Spaces" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Line Length Limit" "10000"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Newline at End of File" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "On-The-Fly Spellcheck" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Overwrite Mode" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "PageUp/PageDown Moves Cursor" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Remove Spaces" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "ReplaceTabsDyn" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Show Spaces" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Show Tabs" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Smart Home" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Swap Directory" ""
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Swap File Mode" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Swap Sync Interval" "15"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Tab Handling" "2"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Tab Width" "4"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Trailing Marker Size" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Word Wrap" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Document" --key "Word Wrap Column" "80"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Editor" --key "Encoding Prober Type" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Editor" --key "Fallback Encoding" "ISO 8859-15"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Animate Bracket Matching" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Auto Color Theme Selection" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Line Height Multiplier" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Show Indentation Lines" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Show Whole Bracket Expression" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor Renderer" --key "Word Wrap Marker" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Allow Mark Menu" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Auto Brackets" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Auto Center Lines" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Auto Completion" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Auto Completion Preselect First Entry" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Backspace Remove Composed Characters" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Bookmark Menu Sorting" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Bracket Match Preview" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Chars To Enclose Selection" "<>(){}[]'\""
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Default Mark Type" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Dynamic Word Wrap" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Dynamic Word Wrap Align Indent" "80"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Dynamic Word Wrap At Static Marker" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Dynamic Word Wrap Indicators" "1"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Dynamic Wrap not at word boundaries" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Fold First Line" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Folding Bar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Folding Preview" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Icon Bar" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Input Mode" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Keyword Completion" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Line Modification" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Line Numbers" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Maximum Search History Size" "100"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Mouse Paste At Cursor Position" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Multiple Cursor Modifier" "134217728"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Persistent Selection" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Bar Marks" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Bar Mini Map All" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Bar Mini Map Width" "60"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Bar MiniMap" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Bar Preview" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Scroll Past End" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Search/Replace Flags" "140"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Documentation With Completion" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Focus Frame Around Editor" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Folding Icons On Hover Only" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Line Count" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Scrollbars" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Show Word Count" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Smart Copy Cut" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Text Drag And Drop" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "User Sets Of Chars To Enclose Selection" ""
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Vi Input Mode Steal Keys" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Vi Relative Line Numbers" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Word Completion" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Word Completion Minimal Word Length" "3"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "KTextEditor View" --key "Word Completion Remove Tail" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "UiSettings" --key "ColorScheme" "Default"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "editShade" "5,88,104"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "listMode" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "shadingEnabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "showCloseButton" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "showFullPathOnRoots" "false"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "showToolbar" "true"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "sortRole" "0"
kwriteconfig5 --file "./conf/etc/xdg/katerc" --group "filetree" --key "viewShade" "58,83,115"
kwriteconfig5 --file "./conf/etc/xdg/plasmashellrc" --group "KFileDialog Settings" --key "detailViewIconSize" "16"
kwriteconfig5 --file "./conf/etc/xdg/plasmashellrc" --group "PlasmaViews" --group "Panel 2" --key "panelVisibility" "1"
kwriteconfig5 --file "./conf/etc/xdg/plasmashellrc" --group "PlasmaViews" --group "Panel 2" --group "Defaults" --key "thickness" "30"
kwriteconfig5 --file "./conf/etc/xdg/filetypesrc" --group "EmbedSettings" --key "embed-application/octet-stream" "false"
kwriteconfig5 --file "./conf/etc/xdg/filetypesrc" --group "EmbedSettings" --key "embed-application/x-wine-extension-ini" "false"
kwriteconfig5 --file "./conf/etc/xdg/kcmshell5rc" --group "UiSettings" --key "ColorScheme" "Default"
kwriteconfig5 --file "./conf/etc/xdg/kiorc" --group "Confirmations" --key "ConfirmDelete" "false"
kwriteconfig5 --file "./conf/etc/xdg/kiorc" --group "Confirmations" --key "ConfirmEmptyTrash" "false"
kwriteconfig5 --file "./conf/etc/xdg/kiorc" --group "Executable scripts" --key "behaviourOnLaunch" "execute"
kwriteconfig5 --file "./conf/etc/xdg/konsolerc" --group "Desktop Entry" --key "DefaultProfile" "Profile 1.profile"
kwriteconfig5 --file "./conf/etc/xdg/konsolerc" --group "UiSettings" --key "ColorScheme" ""
kwriteconfig5 --file "./conf/etc/xdg/konsolerc" --group "UiSettings" --key "WindowColorScheme" "Default"
kwriteconfig5 --file "./conf/etc/xdg/touchpadxlibinputrc" --group "SynPS/2 Synaptics TouchPad" --key "naturalScroll" "true"
kwriteconfig5 --file "./conf/etc/xdg/touchpadxlibinputrc" --group "SynPS/2 Synaptics TouchPad" --key "pointerAccelerationProfileAdaptive" "false"
kwriteconfig5 --file "./conf/etc/xdg/touchpadxlibinputrc" --group "SynPS/2 Synaptics TouchPad" --key "pointerAccelerationProfileFlat" "true"
kwriteconfig5 --file "./conf/etc/xdg/touchpadxlibinputrc" --group "SynPS/2 Synaptics TouchPad" --key "tapDragLock" "true"
kwriteconfig5 --file "./conf/etc/xdg/touchpadxlibinputrc" --group "SynPS/2 Synaptics TouchPad" --key "tapToClick" "true"
kwriteconfig5 --file "./conf/etc/xdg/baloofilerc" --group "General" --key "dbVersion" "2"
kwriteconfig5 --file "./conf/etc/xdg/baloofilerc" --group "General" --key "exclude filters" "*~,*.part,*.o,*.la,*.lo,*.loT,*.moc,moc_*.cpp,qrc_*.cpp,ui_*.h,cmake_install.cmake,CMakeCache.txt,CTestTestfile.cmake,libtool,config.status,confdefs.h,autom4te,conftest,confstat,Makefile.am,*.gcode,.ninja_deps,.ninja_log,build.ninja,*.csproj,*.m4,*.rej,*.gmo,*.pc,*.omf,*.aux,*.tmp,*.po,*.vm*,*.nvram,*.rcore,*.swp,*.swap,lzo,litmain.sh,*.orig,.histfile.*,.xsession-errors*,*.map,*.so,*.a,*.db,*.qrc,*.ini,*.init,*.img,*.vdi,*.vbox*,vbox.log,*.qcow2,*.vmdk,*.vhd,*.vhdx,*.sql,*.sql.gz,*.ytdl,*.class,*.pyc,*.pyo,*.elc,*.qmlc,*.jsc,*.fastq,*.fq,*.gb,*.fasta,*.fna,*.gbff,*.faa,po,CVS,.svn,.git,_darcs,.bzr,.hg,CMakeFiles,CMakeTmp,CMakeTmpQmake,.moc,.obj,.pch,.uic,.npm,.yarn,.yarn-cache,__pycache__,node_modules,node_packages,nbproject,core-dumps,lost+found"
kwriteconfig5 --file "./conf/etc/xdg/baloofilerc" --group "General" --key "exclude filters version" "8"
kwriteconfig5 --file "./conf/etc/xdg/kscreenlockerrc" --group "Greeter" --group "Wallpaper" --group "org.kde.image" --group "General" --key "Image" "/home1/tev/Desktop/background/Anime Street Evening.png"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "normalizeCPUUsage" "true"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "showCommandLineOptions" "false"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "showTooltips" "true"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "showTotals" "true"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "units" "1"
kwriteconfig5 --file "./conf/etc/xdg/systemmonitorrc" --group "TaskDialog" --key "updateIntervalMSecs" "1000"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data" --key "DataCount" "2"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "Comment" "Comment"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "DataCount" "2"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "Enabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "Name" "music"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "SystemGroup" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1" --key "Type" "ACTION_DATA_GROUP"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1Conditions" --key "Comment" ""
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1Conditions" --key "ConditionsCount" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1" --key "Comment" "Comment"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1" --key "Enabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1" --key "Name" "next"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1" --key "Type" "SIMPLE_ACTION_DATA"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Actions" --key "ActionsCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Actions0" --key "CommandURL" "playerctl next"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Actions0" --key "Type" "COMMAND_URL"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Conditions" --key "Comment" ""
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Conditions" --key "ConditionsCount" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Triggers" --key "Comment" "Simple_action"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Triggers" --key "TriggersCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Triggers0" --key "Key" "Alt+Media Play"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Triggers0" --key "Type" "SHORTCUT"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_1Triggers0" --key "Uuid" "{e793c702-98fa-4314-98a2-9aed7662ad13}"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2" --key "Comment" "Comment"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2" --key "Enabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2" --key "Name" "prev"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2" --key "Type" "SIMPLE_ACTION_DATA"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Actions" --key "ActionsCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Actions0" --key "CommandURL" "playerctl previous"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Actions0" --key "Type" "COMMAND_URL"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Conditions" --key "Comment" ""
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Conditions" --key "ConditionsCount" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Triggers" --key "Comment" "Simple_action"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Triggers" --key "TriggersCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Triggers0" --key "Key" "Ctrl+Media Play"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Triggers0" --key "Type" "SHORTCUT"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_1_2Triggers0" --key "Uuid" "{f78700e1-1af3-4a00-8bfc-1abc66d68a91}"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "Comment" "Comment"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "DataCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "Enabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "Name" "flameshot"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "SystemGroup" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2" --key "Type" "ACTION_DATA_GROUP"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2Conditions" --key "Comment" ""
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2Conditions" --key "ConditionsCount" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1" --key "Comment" "Comment"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1" --key "Enabled" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1" --key "Name" "open"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1" --key "Type" "SIMPLE_ACTION_DATA"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Actions" --key "ActionsCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Actions0" --key "CommandURL" "flameshot gui"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Actions0" --key "Type" "COMMAND_URL"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Conditions" --key "Comment" ""
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Conditions" --key "ConditionsCount" "0"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Triggers" --key "Comment" "Simple_action"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Triggers" --key "TriggersCount" "1"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Triggers0" --key "Key" "Meta+Shift+S"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Triggers0" --key "Type" "SHORTCUT"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Data_2_1Triggers0" --key "Uuid" "{2b622f4b-e7dd-4cb3-a362-b4bb59688264}"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Notification Messages" --key "ConfirmDelete" "true"
kwriteconfig5 --file "./conf/etc/xdg/khotkeysrc" --group "Notification Messages" --key "ConfirmEmptyTrash" "true"
kwriteconfig5 --file "./conf/etc/xdg/ksmserverrc" --group "General" --key "loginMode" "emptySession"
kwriteconfig5 --file "./conf/etc/xdg/ksmserverrc" --group "General" --key "confirmLogout" "false"
kwriteconfig5 --file "./conf/etc/xdg/ksmserverrc" --group "LegacySession: saved at previous logout" --key "count" "0"
kwriteconfig5 --file "./conf/etc/xdg/kcminputrc" --group "Mouse" --key "XLbInptAccelProfileFlat" "true"
kwriteconfig5 --file "./conf/etc/xdg/kcminputrc" --group "Mouse" --key "XLbInptPointerAcceleration" "1"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "BackgroundAlternate" "64,69,82"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "BackgroundNormal" "29,31,35"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundActive" "61,174,233"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundLink" "41,128,185"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundNormal" "195,199,209"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Button" --key "ForegroundVisited" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "BackgroundAlternate" "20,20,33"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "BackgroundNormal" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundActive" "0,193,228"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundLink" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Complementary" --key "ForegroundVisited" "124,183,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "BackgroundAlternate" "20,20,33"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "BackgroundNormal" "26,28,32"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundActive" "0,193,228"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundLink" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --key "ForegroundVisited" "124,183,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "BackgroundAlternate" "20,20,33"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "BackgroundNormal" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundActive" "0,193,228"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundLink" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Header" --group "Inactive" --key "ForegroundVisited" "124,183,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "BackgroundAlternate" "29,153,243"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "BackgroundNormal" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundActive" "252,252,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundInactive" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundLink" "253,188,75"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundNormal" "254,254,254"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Selection" --key "ForegroundVisited" "189,195,199"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "BackgroundAlternate" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "BackgroundNormal" "53,57,69"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundActive" "61,174,233"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundLink" "41,128,185"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Tooltip" --key "ForegroundVisited" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "BackgroundAlternate" "20,20,33"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "BackgroundNormal" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "DecorationFocus" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundActive" "0,193,228"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundLink" "33,135,252"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:View" --key "ForegroundVisited" "124,183,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "BackgroundAlternate" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "BackgroundNormal" "26,28,32"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "DecorationFocus" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "DecorationHover" "66,14,210"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundActive" "61,174,233"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundInactive" "102,106,115"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundLink" "41,128,185"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundNegative" "109,69,255"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundNeutral" "255,106,0"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundNormal" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundPositive" "113,247,159"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Colors:Window" --key "ForegroundVisited" "179,13,191"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "General" --key "BrowserApplication" "firefox.desktop"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "Icons" --key "Theme" "Papirus-Dark"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KDE" --key "AnimationDurationFactor" "0.3"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KDE" --key "ColorScheme" "BreezeLight"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KDE" --key "LookAndFeelPackage" "Arch"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KDE" --key "SingleClick" "false"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KDE" --key "contrast" "4"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Allow Expansion" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Automatically select filename extension" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Breadcrumb Navigation" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show Bookmarks" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show Full Path" "false"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show Inline Previews" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show Preview" "false"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show Speedbar" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Show hidden files" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Sort by" "Date"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Sort directories first" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "Sort reversed" "true"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "KFileDialog Settings" --key "View Style" "DetailTree"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "activeBackground" "26,28,32"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "activeBlend" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "activeForeground" "211,218,227"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "inactiveBackground" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "inactiveBlend" "30,32,36"
kwriteconfig5 --file "./conf/etc/xdg/kdeglobals" --group "WM" --key "inactiveForeground" "102,106,115"
